"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-07 15:22:42.611162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('insiders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_institution', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insiders_cik'), 'insiders', ['cik'], unique=True)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_price_data_date'), 'price_data', ['date'], unique=False)
    op.create_index(op.f('ix_price_data_ticker'), 'price_data', ['ticker'], unique=False)
    op.create_table('short_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('short_volume', sa.BigInteger(), nullable=False),
    sa.Column('short_exempt_volume', sa.BigInteger(), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_short_volume_day')
    )
    op.create_index(op.f('ix_short_volume_date'), 'short_volume', ['date'], unique=False)
    op.create_index(op.f('ix_short_volume_ticker'), 'short_volume', ['ticker'], unique=False)
    op.create_table('company_filing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('items', sa.String(), nullable=True),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('primary_document', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_company_filing_events_company_id'), 'company_filing_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_filing_events_filing_date'), 'company_filing_events', ['filing_date'], unique=False)
    op.create_index(op.f('ix_company_filing_events_form_type'), 'company_filing_events', ['form_type'], unique=False)
    op.create_table('earnings_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('report_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'earnings_date', name='uq_company_earnings_date')
    )
    op.create_index(op.f('ix_earnings_dates_company_id'), 'earnings_dates', ['company_id'], unique=False)
    op.create_index(op.f('ix_earnings_dates_earnings_date'), 'earnings_dates', ['earnings_date'], unique=False)
    op.create_table('form4_filing_meta',
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_index(op.f('ix_form4_filing_meta_company_id'), 'form4_filing_meta', ['company_id'], unique=False)
    op.create_index(op.f('ix_form4_filing_meta_filing_date'), 'form4_filing_meta', ['filing_date'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'concept', 'period_end', 'filed_date', name='uq_fundamental_fact')
    )
    op.create_index(op.f('ix_fundamentals_company_id'), 'fundamentals', ['company_id'], unique=False)
    op.create_index(op.f('ix_fundamentals_concept'), 'fundamentals', ['concept'], unique=False)
    op.create_index(op.f('ix_fundamentals_filed_date'), 'fundamentals', ['filed_date'], unique=False)
    op.create_table('insider_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=False),
    sa.Column('first_filing_date', sa.Date(), nullable=True),
    sa.Column('last_filing_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_roles_company_id'), 'insider_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_insider_roles_insider_id'), 'insider_roles', ['insider_id'], unique=False)
    op.create_table('insider_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('num_discretionary_buys', sa.Integer(), nullable=False),
    sa.Column('raw_hit_rate', sa.Float(), nullable=True),
    sa.Column('bayesian_hit_rate', sa.Float(), nullable=True),
    sa.Column('confidence_above_baseline', sa.Float(), nullable=True),
    sa.Column('avg_excess_return', sa.Float(), nullable=True),
    sa.Column('shrunk_excess_return', sa.Float(), nullable=True),
    sa.Column('momentum_adjusted_excess', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('credibility_weight', sa.Float(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('credibility_tier', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insider_id', 'company_id', name='uq_insider_company_score')
    )
    op.create_index(op.f('ix_insider_scores_insider_id'), 'insider_scores', ['insider_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('shares_owned_after', sa.Float(), nullable=True),
    sa.Column('acquired_or_disposed', sa.String(), nullable=False),
    sa.Column('is_discretionary', sa.Boolean(), nullable=False),
    sa.Column('security_title', sa.String(), nullable=True),
    sa.Column('is_common_stock', sa.Boolean(), nullable=True),
    sa.Column('is_10b5_1_plan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_filing_date'), 'transactions', ['filing_date'], unique=False)
    op.create_index(op.f('ix_transactions_insider_id'), 'transactions', ['insider_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('conviction_score', sa.Float(), nullable=False),
    sa.Column('insider_skill_score', sa.Float(), nullable=False),
    sa.Column('transaction_value', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_trade_date'), 'alerts', ['trade_date'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('simulated_alert_type', sa.String(), nullable=False),
    sa.Column('simulated_conviction', sa.Float(), nullable=False),
    sa.Column('simulated_skill_score', sa.Float(), nullable=False),
    sa.Column('simulated_tier', sa.String(), nullable=False),
    sa.Column('num_prior_buys', sa.Integer(), nullable=False),
    sa.Column('actual_return_20d', sa.Float(), nullable=True),
    sa.Column('actual_return_60d', sa.Float(), nullable=True),
    sa.Column('actual_return_120d', sa.Float(), nullable=True),
    sa.Column('actual_excess_20d', sa.Float(), nullable=True),
    sa.Column('actual_excess_60d', sa.Float(), nullable=True),
    sa.Column('actual_excess_120d', sa.Float(), nullable=True),
    sa.Column('actual_hit_20d', sa.Boolean(), nullable=True),
    sa.Column('actual_hit_60d', sa.Boolean(), nullable=True),
    sa.Column('actual_hit_120d', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_run_id'), 'backtest_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_transaction_date'), 'backtest_results', ['transaction_date'], unique=False)
    op.create_table('form4_deriv_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('deriv_trans_sk', sa.BigInteger(), nullable=False),
    sa.Column('security_title', sa.String(), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('trans_code', sa.String(), nullable=True),
    sa.Column('conv_exercise_price', sa.Float(), nullable=True),
    sa.Column('trans_shares', sa.Float(), nullable=True),
    sa.Column('trans_price_per_share', sa.Float(), nullable=True),
    sa.Column('acquired_disposed', sa.String(length=1), nullable=True),
    sa.Column('exercisable_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('underlying_shares', sa.Float(), nullable=True),
    sa.Column('shares_owned_after', sa.Float(), nullable=True),
    sa.Column('timeliness', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['form4_filing_meta.accession_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'deriv_trans_sk', name='uq_form4_deriv_row')
    )
    op.create_index(op.f('ix_form4_deriv_txns_accession_number'), 'form4_deriv_txns', ['accession_number'], unique=False)
    op.create_index(op.f('ix_form4_deriv_txns_trans_date'), 'form4_deriv_txns', ['trans_date'], unique=False)
    op.create_table('form4_footnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('footnote_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['form4_filing_meta.accession_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'footnote_id', name='uq_form4_footnote')
    )
    op.create_index(op.f('ix_form4_footnotes_accession_number'), 'form4_footnotes', ['accession_number'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('stock_return_20d', sa.Float(), nullable=True),
    sa.Column('stock_return_60d', sa.Float(), nullable=True),
    sa.Column('stock_return_120d', sa.Float(), nullable=True),
    sa.Column('benchmark_return_20d', sa.Float(), nullable=True),
    sa.Column('benchmark_return_60d', sa.Float(), nullable=True),
    sa.Column('benchmark_return_120d', sa.Float(), nullable=True),
    sa.Column('sector_return_20d', sa.Float(), nullable=True),
    sa.Column('sector_return_60d', sa.Float(), nullable=True),
    sa.Column('sector_return_120d', sa.Float(), nullable=True),
    sa.Column('excess_return_20d', sa.Float(), nullable=True),
    sa.Column('excess_return_60d', sa.Float(), nullable=True),
    sa.Column('excess_return_120d', sa.Float(), nullable=True),
    sa.Column('prior_momentum_20d', sa.Float(), nullable=True),
    sa.Column('hit_20d', sa.Boolean(), nullable=True),
    sa.Column('hit_60d', sa.Boolean(), nullable=True),
    sa.Column('hit_120d', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('broker_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=True),
    sa.Column('alpaca_order_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('extended_hours', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=True),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('sizing_method', sa.String(), nullable=True),
    sa.Column('sizing_vol', sa.Float(), nullable=True),
    sa.Column('sizing_pct', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['broker_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpaca_order_id')
    )
    op.create_index(op.f('ix_broker_orders_alert_id'), 'broker_orders', ['alert_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_status'), 'broker_orders', ['status'], unique=False)
    op.create_index(op.f('ix_broker_orders_symbol'), 'broker_orders', ['symbol'], unique=False)
    op.create_table('broker_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=False),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('last_market_price', sa.Float(), nullable=True),
    sa.Column('reconcile_hold', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('insider_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['broker_orders.id'], ),
    sa.ForeignKeyConstraint(['exit_order_id'], ['broker_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_broker_positions_status'), 'broker_positions', ['status'], unique=False)
    op.create_index(op.f('ix_broker_positions_symbol'), 'broker_positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_positions_symbol'), table_name='broker_positions')
    op.drop_index(op.f('ix_broker_positions_status'), table_name='broker_positions')
    op.drop_table('broker_positions')
    op.drop_index(op.f('ix_broker_orders_symbol'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_status'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_alert_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    op.drop_table('trade_outcomes')
    op.drop_index(op.f('ix_form4_footnotes_accession_number'), table_name='form4_footnotes')
    op.drop_table('form4_footnotes')
    op.drop_index(op.f('ix_form4_deriv_txns_trans_date'), table_name='form4_deriv_txns')
    op.drop_index(op.f('ix_form4_deriv_txns_accession_number'), table_name='form4_deriv_txns')
    op.drop_table('form4_deriv_txns')
    op.drop_index(op.f('ix_backtest_results_transaction_date'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_run_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_alerts_trade_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_insider_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_filing_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_insider_scores_insider_id'), table_name='insider_scores')
    op.drop_table('insider_scores')
    op.drop_index(op.f('ix_insider_roles_insider_id'), table_name='insider_roles')
    op.drop_index(op.f('ix_insider_roles_company_id'), table_name='insider_roles')
    op.drop_table('insider_roles')
    op.drop_index(op.f('ix_fundamentals_filed_date'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_concept'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_company_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_form4_filing_meta_filing_date'), table_name='form4_filing_meta')
    op.drop_index(op.f('ix_form4_filing_meta_company_id'), table_name='form4_filing_meta')
    op.drop_table('form4_filing_meta')
    op.drop_index(op.f('ix_earnings_dates_earnings_date'), table_name='earnings_dates')
    op.drop_index(op.f('ix_earnings_dates_company_id'), table_name='earnings_dates')
    op.drop_table('earnings_dates')
    op.drop_index(op.f('ix_company_filing_events_form_type'), table_name='company_filing_events')
    op.drop_index(op.f('ix_company_filing_events_filing_date'), table_name='company_filing_events')
    op.drop_index(op.f('ix_company_filing_events_company_id'), table_name='company_filing_events')
    op.drop_table('company_filing_events')
    op.drop_index(op.f('ix_short_volume_ticker'), table_name='short_volume')
    op.drop_index(op.f('ix_short_volume_date'), table_name='short_volume')
    op.drop_table('short_volume')
    op.drop_index(op.f('ix_price_data_ticker'), table_name='price_data')
    op.drop_index(op.f('ix_price_data_date'), table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_insiders_cik'), table_name='insiders')
    op.drop_table('insiders')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
